FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY publisher.py publisher.py

CMD ["uvicorn", "publisher:app", "--host", "0.0.0.0", "--port", "8000"]
